### ISSUE TITLE
cheat wont inject, config system crash

### ISSUE THREAD

**Issue by designer1337** [patrykkolodziej/Explit#3]
as above, debbuger output
![Screenshot_6](https://user-images.githubusercontent.com/25611750/57528639-2acb3e80-7333-11e9-8bf3-ea06fdbae154.png)

**Comment by patrykkolodziej** [comment]
Create manually this folder. As I said in "Public release" commit, config system isn't ended yet and need some fixes.

**Comment by patrykkolodziej** [comment]
#Fixed
